# This file was generated by GoReleaser. DO NOT EDIT.
cask "ddcli" do
  name "ddcli"
  desc "Datadog CLI for AI agents and humans"
  homepage "https://github.com/ethanrcohen/ddcli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ddcli"

  on_macos do
    on_intel do
      url "https://github.com/ethanrcohen/ddcli/releases/download/v#{version}/ddcli_darwin_amd64.tar.gz"
      sha256 "08ad18fefa074f154b368eafde7bf92422970421052151b7ce4f3629c003b879"
    end
    on_arm do
      url "https://github.com/ethanrcohen/ddcli/releases/download/v#{version}/ddcli_darwin_arm64.tar.gz"
      sha256 "08073324df3fc4fc2ac73c80ff0cf02181c0fc64c5d156ed94a6b55e74679acc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ethanrcohen/ddcli/releases/download/v#{version}/ddcli_linux_amd64.tar.gz"
      sha256 "5230b413a55f4330c067efc09803dbe18f608d7f56c5bfdcb6a120bfb4d7cde5"
    end
    on_arm do
      url "https://github.com/ethanrcohen/ddcli/releases/download/v#{version}/ddcli_linux_arm64.tar.gz"
      sha256 "19763b29ada80f5bae30aa87c9b988370c8e6f46635df8b1fe2fb8853ce863d7"
    end
  end

  # No zap stanza required
end
